---
- name: Fetch the kubectl SHA256 checksum
  uri:
    url: "{{ kubectl_checksum_url }}"
    return_content: true
  register: kubectl_sha256

- name: Download the kubectl binary.
  get_url:
    url: "{{ kubectl_download_url }}"
    dest: "{{ kubectl_bin_path }}"
    checksum: sha256:{{ kubectl_sha256.content }}
    mode: 0755
  become: true
